name: mawstool 
summary: Tools for interacting with awscli
description: |
  This tool aims to make interacting with awscli a little bit easier by
  using variable environment variables and handling the awscli syntax.

base: core22
type: app
version: 0.1.0
grade: stable
confinement: strict

apps:
  mitch-awstool:
    command: bin/mawstool
    plugs:
      - network
      - home
    aliases:
      - mawstool 

parts:
  mawstool:
    source: .
    plugin: dump
    organize:
            mawstool: bin/mawstool
